### ISSUE TITLE
Possible Additional Function

### ISSUE THREAD

**Issue by mtnbkr88** [tanaka42/androidapp-websoundcontrol#1]
Hi. On an Android you can usually use the volume up or volume down buttons to take a picture when the native camera app is open. I hoped your simple lite weight program would do that but picking volume up or down through your app does not take the picture on the Android. Is it possible you could add a third button to take a remote picture? I know. It's a lot to ask, but I think it might be handy. Thank you

**Comment by tanaka42** [comment]
Hi,

sorry, I will not do this, this is why :

I understand this may be useful per example to take group pictures.

This is completely possible and probably easy to do.

But I am very concerned by the fact some people may use it to take pictures of other people without them knowing (even with the local network limitation : roomates). I have been thinking about it a lot and I can't figure out how to prevent this reliably.

Sorry again...

Thank you for your suggestion anyway.

With kind regards
